services:
  model-api:
    image: sotsuba/lossteach-gdgaic-model-api:latest
    container_name: gdgaic-model-api
    build:
      context: app/model-api
      dockerfile: Dockerfile
    ports:
    - 5000:5000
    - 8099:8099
    networks:
      - gdgaic-network
    environment:
      - HOST=0.0.0.0
      - PORT=5000


  prometheus:
    image: prom/prometheus:v2.38.0
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - prometheus_data:/prometheus
      - ./observe/prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./observe/prometheus/config/alert-rules.yml:/etc/prometheus/alert-rules.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=20h'
      - '--web.enable-lifecycle'
    ports:
      - 9090:9090
    networks:
      - gdgaic-network

  dashboard:
    image: sotsuba/lossteach-gdgaic-dashboard:latest
    container_name: gdgaic-dashboard
    build:
      context: app/dashboard
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      model-api:
        condition: service_healthy
    networks:
      - gdgaic-network
    environment:
      - MODEL_API_URL=http://model-api:5000
      - HOST=0.0.0.0
      - PORT=8501

  alertmanager:
    image: prom/alertmanager:v0.25.0
    container_name: alertmanager
    restart: unless-stopped
    volumes:
      - alertmanager_data:/alertmanager/data
      - ./observe/alertmanager:/alertmanager
    command:
      - '--config.file=/alertmanager/config.yml'
      - '--storage.path=/alertmanager/data'
      - '--log.level=debug'
    ports:
      - 9093:9093
    networks:
      - gdgaic-network

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    restart: unless-stopped
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
    ports:
      - 8090:8080
    networks:
      - gdgaic-network

  grafana:
    image: grafana/grafana:9.0.5
    container_name: grafana
    restart: unless-stopped
    volumes:
      - grafana_data:/var/lib/grafana
      - ./observe/grafana/config/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml:ro
      - ./observe/grafana/config/datasources.yaml:/etc/grafana/provisioning/datasources/datasource.yaml:ro
      - ./observe/grafana/dashboards:/opt/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
    ports:
      - 3000:3000
    networks:
      - gdgaic-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f localhost:3000/api/health && echo 'ready'"]
      interval: 10s
      retries: 10         

  node-exporter:
    image: prom/node-exporter:v1.3.1
    container_name: node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - 9100:9100
    networks:
      - gdgaic-network

volumes:
  prometheus_data:
  grafana_data:
  alertmanager_data:

networks:
  gdgaic-network:
    name: gdgaic-network
    driver: bridge

